name: Headway Health and Fitness
favicon: null
layout_spectrum: 0.4393
typography_spectrum: 0.38907
title: Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#35256c'
    - '#8d8ebe'
    - '#584a95'
    - '#3d689a'
    - '#d6c0c3'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
