name: Headway Health and Fitness
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7a49b1'
    - '#80b24a'
    - '#027daa'
    - '#022a63'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
