name: Headway Health and Fitness
favicon: null
layout_spectrum: 0.57273
typography_spectrum: 0
title: HEADWAY Health and Fitness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#35256c'
    - '#8d8ebe'
    - '#584a95'
    - '#3d689a'
    - '#d6c0c3'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
