name: Headway Health and Fitness
favicon: null
layout_spectrum: 0.4393
typography_spectrum: 0.51326
title: Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7a49b1'
    - '#80b24a'
    - '#027daa'
    - '#022a63'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
